export const ActionTypes = {
  FETCH_IMAGE_START: 'FETCH_IMAGE_START',
  FETCH_IMAGE_FAIL: 'FETCH_IMAGE_FAIL',
  FETCH_IMAGE_SUCCEED: 'FETCH_IMAGE_SUCCEED',
  FETCH_INFO_START: 'FETCH_INFO_START',
  FETCH_INFO_FAIL: 'FETCH_INFO_FAIL',
  FETCH_INFO_SUCCEED: 'FETCH_INFO_SUCCEED',
  CHANGE_LATENTS: 'CHANGE_LATENTS',
  CHANGE_PSI: 'CHANGE_PSI',
  RANDOM_LATENTS: 'RANDOM_LATENTS',
  CHANGE_LABEL: 'CHANGE_LABEL'
}